name: Render BTC Chart

on:
  schedule:
    - cron: '*/5 * * * *' # každých 5 minut
  workflow_dispatch:      # umožňuje ruční spuštění z GitHub rozhraní

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
          npm install

      - name: Run render script
        run: node render.js
