name: Render BTC Chart

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev
          npm ci

      - name: Run render.js
        run: node render.js

      - name: Commit and push chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x  # pro ladění

          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          # Před jakýmkoliv commitem MUSÍ být aktuální historie!
          git pull origin main --rebase

          git add btc-chart.png
          git diff --staged --quiet && echo "No changes to commit." && exit 0
          git commit -m "Auto update chart [skip ci]"

          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main --force-with-lease
