name: Render BTC Chart

on:
  schedule:
    - cron: '*/5 * * * *'  # Spouští každých 5 minut
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    
    # NOVÁ DŮLEŽITÁ ČÁST: Přidání oprávnění pro GITHUB_TOKEN
    permissions:
      contents: write # Toto dává botovi oprávnění k zápisu do repozitáře

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev
          npm install

      - name: Run render.js
        run: node render.js

      - name: Commit and push chart
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add btc-chart.png
          git commit -m "Auto update chart [skip ci]" || echo "No changes to commit"

          echo "Attempting git pull..." # Přidáno pro ladění
          git pull origin main --rebase # Zkuste to znovu s ověřením
          if [ $? -ne 0 ]; then # Zkontroluje, zda git pull selhal
              echo "Git pull failed, attempting force-with-lease..."
              git push origin main --force-with-lease # Záložní řešení
          else
              echo "Git pull successful, attempting regular push..."
              git push origin main
          fi
