name: Render BTC Chart

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # nutné pro push s GitHub tokenem

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # DŮLEŽITÉ – stáhne celou historii, nutné pro git pull

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev
          npm ci

      - name: Run render.js
        run: node render.js

      - name: Commit and push chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add btc-chart.png
          git commit -m "Auto update chart [skip ci]" || echo "No changes to commit, skipping commit"

          # Použijeme git push --force-with-lease
          # To je bezpečnější než --force, protože pushne jen tehdy, pokud se vzdálená historie
          # nezměnila od posledního fetch (který zajistil actions/checkout s fetch-depth: 0).
          # Tím se vyhneme potenciálnímu přepsání cizích změn.
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main --force-with-lease || echo "Failed to force-push, there might be new commits on remote."
